export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_CURRENT_CATEGORY_NAME = "FETCH_CURRENT_CATEGORY_NAME";

export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const CHANGE_CURRENCY_SYMBOL = "CHANGE_CURRENCY_SYMBOL";
export const TOGGLE_CART_OVERLAY = "TOGGLE_CART_OVERLAY";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_QTY = "INCREMENT_QTY";
export const DECREMENT_QTY = "DECREMENT_QTY";

export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const SELECTED_ATTRIBUTES = "SELECTED_ATTRIBUTES";